### PR TITLE
[goldilocks] enable to pull uninstall image from custom repository

### PR DESCRIPTION
**Pull request by yasintahaerol**
**Why This PR?**
_a short description of why this PR is needed_

This image was pulling from a constant repository. Some developers or organizations want to use own their repository. It will be enabled to use custom repository by this feature.

Fixes #

It will be enabled to use custom repository by this feature.

**Changes**
Changes proposed in this pull request:

*
*

**Checklist:**

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] Any new values have been added to the README for the Chart, or helm-docs has been run for the charts that support it.

### CODE REVIEW

**Comment by sudermanjr** [comment]
This look like a duplicate of #604 which was closed. Am I missing something here?

**Comment by yasintahaerol** [comment]
Yes, it is same. First time I used helm-docs and could not figure out how it works. Because of this reason I closed to old one and want to make fresh start. I hope everything is okey 🙏

**Comment by sudermanjr** [comment]
@yasintahaerol We are actually planning to deprecate this feature (uninstallVPA) soon, especially since it is only needed to upgrade from very old versions of this chart. I don't think we should continue to update a feature that's going to be removed.

@lucasreed please correct me if I'm wrong.

**Comment by yasintahaerol** [comment]
thaks, yes i aggree with you. I closed the PR.

**Pull request closed without merging**
