### PR TITLE
add prometheus rbac

### PR DESCRIPTION
**Pull request by dza89**
**Why This PR?**
```
ime="2021-02-11T14:12:00Z" level=warning msg="Error retrieving parent object API v1 and Kind alertmanagers because of error: alertmanagers.monitoring.coreos.com is forbidden: User \"system:serviceaccount:cpt:polaris\" cannot list resource \"alertmanagers\" in API group \"monitoring.coreos.com\" at the cluster scope"
time="2021-02-11T14:12:00Z" level=warning msg="Error caching objects of Kind Alertmanager alertmanagers.monitoring.coreos.com is forbidden: User \"system:serviceaccount:cpt:polaris\" cannot list resource \"alertmanagers\" in API group \"monitoring.coreos.com\" at the cluster scope"
time="2021-02-11T14:12:00Z" level=warning msg="Error retrieving parent object API v1 and Kind prometheuses because of error: prometheuses.monitoring.coreos.com is forbidden: User \"system:serviceaccount:cpt:polaris\" cannot list resource \"prometheuses\" in API group \"monitoring.coreos.com\" at the cluster scope"
```

Fixes #

Update RBAC

**Checklist:**

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] Any new values have been added to the README for the Chart, or helm-docs has been run for the charts that support it.

### CODE REVIEW

**Comment by dza89** [comment]
I can't fix this.

```time="2021-02-11T15:11:19Z" level=fatal msg="FAIRWINDS_TOKEN environment variable not set"```

**Comment by rbren** [comment]
I think we need to manually run that Insights test to get the token set - trying now.

**Comment by dza89** [comment]
Well it's not required? :p

**Comment by rbren** [comment]
Sorry @dza89 looks like we lost track of this - updating && merging

**Pull request merged**
