### PR TITLE
Update Goldilocks API Versions and Chart Testing

### PR DESCRIPTION
**Pull request by sudermanjr**

### CODE REVIEW

**Comment by rbren** [comment]
Do we also need to update the vpa-installer since the current version uses `extensions/v1beta1/Deployment`?

```
unable to recognize "deploy/recommender-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
```

**Comment by sudermanjr** [comment]
Unfortunately that's an issue upstream.  I'll take a look

**Comment by sudermanjr** [comment]
Looks like they updated it, but didn't release. I'm looking for a commit we can pin to

**Comment by sudermanjr** [comment]
I pushed something up. @rbren if you could test that I would very much appreciate it.

**Review by ejether — APPROVED** [review]

**Comment by sudermanjr** [comment]
Just FYI, I tested on kube 1.16 in a kind cluster.

**Pull request merged**
