### PR TITLE
Helm3 e2e. Helm-docs. Api v2 support. Add clamav chart.

### PR DESCRIPTION
**Pull request by sudermanjr**
Adding helm-docs
Adding note about helm-docs to the CONTRIBUTING
Goldilocks helm-docs
e2e tests are only Helm3 now.
chart linting supports api v2
chart install timeout increased
add --upgrade flag to ct install

### CODE REVIEW

**Comment by sudermanjr** [comment]
I have an open issue with chart-test to figure out why we can't run `ct lint` on a schema v2 chart.

https://github.com/helm/chart-testing/issues/209

**Comment by sudermanjr** [comment]
> I have an open issue with chart-test to figure out why we can't run `ct lint` on a schema v2 chart.
> 
> [helm/chart-testing#209](https://github.com/helm/chart-testing/issues/209)

This ended up being my mistake but was just badly reported by chart-testing. Hopefully fixed in later releases.

**Review by bambash — APPROVED** [review]
Looks great, thanks for cleaning things up and adding support for Helm 3! I tried installing the clamav chart, but the server is crashlooping:
```
LibClamAV Error: cli_loaddbdir(): No supported database files found in /data
```

I'm not familiar with clamav, but the chart looks great

**Comment by sudermanjr** [comment]
> ```
> LibClamAV Error: cli_loaddbdir(): No supported database files found in /data
> ```

That's odd. The e2e should cover that, and my other testing did as well. I'll take a look before I merge

**Pull request merged**
