### PR TITLE
[stable/rbac-manager] Make securityContext configurable

### LINKED ISSUE #1006: [rbac-manager] Make securityContext for pod and container configurable
**Is your feature request related to a problem? Please describe.**
Using the [Pod Security Standard "restricted" level](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted) requires certain securityContext settings to be set. While the container of rbac-manager actually already fulfills most of the requirements (uid has to be explicitly set if the container image uses a named user) the mandatory seccompProfile is missing and since the securityContext for neither pod nor container is configurable this cannot be amended trivially.

**Describe the solution you'd like**
Ideally the current values of the container's `securityContext` would be moved to values.yaml and additionally `podSecurityContext` be made available via values.yaml, too. This would mirror the behaviour of default charts created by `helm create <chart name>` and be fully backwards compatible.

**Describe alternatives you've considered**
One could probably use kustomize to modify the deployment post-rendering. Since PSS/PSA are default features it will likely be desirable to have a more straightforward solution though.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by manzsolutions-lpr**
**Why This PR?**
Using the [Pod Security Standard "restricted" level](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted) requires certain securityContext settings to be set. While the container of rbac-manager actually already fulfills most of the requirements (uid has to be explicitly set if the container image uses a named user) the mandatory seccompProfile is missing and since the securityContext for neither pod nor container is configurable this cannot be amended trivially. This PR makes securityContext for both the pod and container fully configurable via values.yaml.

Fixes #1006

**Changes**
Changes proposed in this pull request:

* Move container securityContext values to values.yaml as defaults for securityContext
* Add podSecurityContext in values.yaml which is rendered to securityContext on pod level

**Checklist:**

* [x] I have included the name of the chart in the title of this PR in square brackets i.e. `[stable/goldilocks]`.
* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] Any new values have been added to the README for the Chart, or `helm-docs --sort-values-order=file` has been run for the charts that support it.

### CODE REVIEW

**Review by sudermanjr — APPROVED** [review]
Thanks for the PR! This looks great to me. Just need the CLA signed and we're good to go.

**Comment by manzsolutions-lpr** [comment]
@sudermanjr Wonderful. I’m currently waiting for an official sign-off from the company on the CLA, should not take too long.

**Comment by manzsolutions-lpr** [comment]
Unfortunately the “CLA Assistant” requires privileges far beyond what I would be comfortable with:
github com 2022-11-08 17 36 24 a3e44f43c769

So while I would love to sign the CLA I do not see how without authorizing CLA assistant to that extent and that will not happen. Would you happen to know another way? Or am I misinterpreting something?

**Comment by sudermanjr** [comment]
Great question. I think it should only need that level of access if you are setting it up to run your CLA for your own projects. I don't believe signing it should require it. (it seems like it already has access to your email, which is the only thing it should need for signing)

**Comment by sudermanjr** [comment]
Yeah, if I click on the [sign cla](https://cla-assistant.io/FairwindsOps/charts?pullRequest=1007) link it only asks for email once I sign in

**Comment by manzsolutions-lpr** [comment]
I found the issue. I block cookies by default and cla-assistant.io was not whitelisted yet. But instead of throwing an error the callback instead redirected me back to the authorisation page asking for full admin privileges. :-/

**Pull request merged**
