### PR TITLE
update chart-testing

### PR DESCRIPTION
**Pull request by rbren**
**Why This PR?**
_a short description of why this PR is needed_

Fixes #

**Changes**
Changes proposed in this pull request:

*
*

**Checklist:**

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] Any new values have been added to the README for the Chart, or helm-docs has been run for the charts that support it.

### CODE REVIEW

**Review by sudermanjr — CHANGES_REQUESTED** [review]
Should we go ahead and drop 1.16 and 1.17 so we're not running quite so many tests?

**Comment by rbren** [comment]
1.21 isn't working out of the box (maybe a rok8s orb issue?) so I'm going w/ 1.17-20 for now

**Comment by rbren** [comment]
@sudermanjr IIRC this workflow only runs on _changed_ charts to save time. Any idea how we can test the transition before we break every chart's build?

**Review by sudermanjr — CHANGES_REQUESTED** [review]
I think this went a bit stale and needs a rebase

**Comment by rbren** [comment]
Something is funky with 1.20 :/

**Comment by rbren** [comment]
For visibility - I've tracked the issue down to PersistentVolumeClaims not getting provisioned. 

```
bash-5.1# k get pvc
NAME                                              STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-fairwinds-insights-pwvxnu7xu1-postgresql-0   Pending                                      hostpath       12m
fairwinds-insights-pwvxnu7xu1-fw-minio            Pending                                      hostpath       11m
```

```
bash-5.1# k describe pvc data-fairwinds-insights-pwvxnu7xu1-postgresql-0
Name:          data-fairwinds-insights-pwvxnu7xu1-postgresql-0
Namespace:     fairwinds-insights-pwvxnu7xu1
StorageClass:  hostpath
Status:        Pending
Volume:
Labels:        app.kubernetes.io/instance=fairwinds-insights-pwvxnu7xu1
               app.kubernetes.io/name=postgresql
               role=master
Annotations:   volume.beta.kubernetes.io/storage-provisioner: hostpath
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       fairwinds-insights-pwvxnu7xu1-postgresql-0
Events:
  Type    Reason                Age                   From                         Message
  ----    ------                ----                  ----                         -------
  Normal  ExternalProvisioning  2m46s (x43 over 12m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "hostpath" or manually created by system administrator
```

**Comment by makoscafee** [comment]
mmh what is  `VolumeBindMode` if you `k describe sc hostpath`?  if is `WaitForFirstConsumer` then it will remain in pending state until a pod consumes it.

**Comment by rbren** [comment]
Good call Barnie!

Here's the underlying issue: https://github.com/rimusz/hostpath-provisioner/issues/8

Looks like we need to change the rok8s-scripts orb in order to implement the workaround there...

**Comment by rbren** [comment]
@sudermanjr I abandoned the new k8s versions and am just updating chart-testing - should be good to go once CI passes

**Review by sudermanjr — APPROVED** [review]

**Pull request merged**
