### PR TITLE
Make Trivy filesystem writeable

### PR DESCRIPTION
**Pull request by baderbuddy**
Trivy broke with readonly root.

### CODE REVIEW

**Review by rbren — APPROVED** [review]

**Comment by sudermanjr** [comment]
Is it possible to instead mount an emptydir in the place where it needs to save files? Allowing root filesystem writes is a security issue.

**Comment by rbren** [comment]
Sadly (AFAICT) trivy does not appear to be readily configurable. This reverts a recent attempt to make the FS read only (for that very reason)

**Comment by sudermanjr** [comment]
Ah, bummer.

**Comment by rbren** [comment]
Hmm wait, might have figured it out...

**Pull request merged**
