### PR TITLE
 [stable/insights-agent] Upgrade trivy plugin version to 0.28

### PR DESCRIPTION
**Pull request by jslivka**
**Why This PR?**
_a short description of why this PR is needed_

Fixes #

**Changes**
Changes proposed in this pull request:

*
*

**Checklist:**

* [x] I have included the name of the chart in the title of this PR in square brackets i.e. `[stable/goldilocks]`.
* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] Any new values have been added to the README for the Chart, or `helm-docs --sort-values-order=file` has been run for the charts that support it.

### CODE REVIEW

**Review by rbren — APPROVED** [review]

**Comment by rbren** [comment]
Screenshot 2023-08-11 at 11 26 03 AM


it looks like maybe kyverno isnt completing?

**Comment by rbren** [comment]
Screenshot 2023-08-11 at 11 28 05 AM

**Comment by jslivka** [comment]
Yeah I enabled this in `test-values.yaml` prematurely. The Kyverno plugin needs the CRDs to be installed:

```
e2e-control-plane:/# kubectl -n insights-agent-xmzst7ya11 logs -f kyverno-28196227-wmj7f
Defaulted container "kyverno" out of: kyverno, insights-uploader
Starting kyverno
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "policies.kyverno.io" not found
```

**Comment by rbren** [comment]
Forced this in since these tests are likely just perma-broken until we do

**Pull request merged**
