### PR TITLE
[polaris] Add annotations to the dashboard service.

### PR DESCRIPTION
**Pull request by titilambert**

### CODE REVIEW

**Comment by rbren** [comment]
Thanks, looks good! Can you just add this option to the README?

**Comment by titilambert** [comment]
> Thanks, looks good! Can you just add this option to the README?

@rbren  Done !

**Review by rbren — APPROVED** [review]

**Comment by titilambert** [comment]
@rbren thanks ! Quick question: How long it takes to get it in a new version after the merge ?

**Comment by sudermanjr** [comment]
> Quick question: How long it takes to get it in a new version after the merge ?

@titilambert I just merged. Once the CI runs the new version should be available for you.

**Comment by titilambert** [comment]
@rbren thanks !

**Pull request merged**
