### PR TITLE
[stable/ecr-cleanup] Allow to specify pod annotations

### PR DESCRIPTION
**Pull request by qiq**
Also update image to latest version.

### CODE REVIEW

**Comment by sudermanjr** [comment]
Thanks for the PR!  Looks like the e2e testing is failing on our end for some reason.  I'm going to take a look and see if I can fix it.

**Comment by sudermanjr** [comment]
@qiq I fixed the issue with our e2e testing. Would you mind rebasing on master so that we can verify?

**Comment by qiq** [comment]
Great! Sure, rebased.

**Comment by qiq** [comment]
Looks good :-)

**Review by sudermanjr — APPROVED** [review]
LGTM.  Thanks for the contribution!

**Pull request merged**
