### PR TITLE
[insights-agent] Fix cron-executor job for Kube v1.21 by downloading kubectl dynamically

### PR DESCRIPTION
**Pull request by ivanfetch**
This addresses bug 24084, and allows the cron executor job (Helm install-hook) to run in Kube 1.21 by downloading the same version of kubectl to match the cluster. If the cluster version is <= 1.19 kubectl 1.19.6 will be used to match the behavior of our previously-used `quay.io/fairwinds/kubectl:0.19` image.
The reason kubectl 1.19 is used for cluster versions older than 1.19, relates to [this kubectl issue about setting the owner information as CronJob belonging to the Apps API Group](https://github.com/kubernetes/kubectl/issues/842).

The cron executor output is nformative about why a particular version of kubectl was chosen (matching the Kube API, falling back to 1.19 for clusters 1.19 and older, or falling back because the kube API could not be queried). This PR also adds some clarifying log output about why Job resources are being deleted then created.

I chose a `curl` base container image to avoid installing a curl package as root, so this job container can continue to run as non-root with a read-only filesystem. The jq and kubectl binaries are directly downloaded and installed in the `/tmp/bin` EmptyDir volume.

Before this PR, the `kubectl create job --from=CronJob/...` kubectl syntax failed when using earlier versions of kubectl with Kube 1.21, because the status of CronJob resources graduated in Kube 1.21. This failure logged errors such as: `error: from must be an existing cronjob: no kind "CronJob" is registered for version "batch/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"`

Here is output from the cron-executor pod in Kube 1.21.1:

```
Downloading jq . . .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   614  100   614    0     0   1726      0 --:--:-- --:--:-- --:--:--  1729
100 3861k  100 3861k    0     0  2296k      0  0:00:01  0:00:01 --:--:-- 3656k
Getting the Kubernetes version from the API. . .
Using kubectl version v1.21.1 to match the cluster
Downloading kubectl version v1.21.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154  100   154    0     0    627      0 --:--:-- --:--:-- --:--:--   628
100 45.3M  100 45.3M    0     0  9149k      0  0:00:05  0:00:05 --:--:-- 11.0M
Cleaning up old jobs. . .
job.batch "goldilocks" deleted
job.batch "kube-bench" deleted
job.batch "kube-hunter" deleted
job.batch "nova" deleted
job.batch "opa" deleted
job.batch "pluto" deleted
job.batch "polaris" deleted
job.batch "rbac-reporter" deleted
job.batch "trivy" deleted
job.batch "workloads" deleted
Creating jobs. . .
job.batch/goldilocks created
job.batch/kube-bench created
job.batch/kube-hunter created
job.batch/nova created
job.batch/opa created
job.batch/pluto created
job.batch/polaris created
job.batch/rbac-reporter created
job.batch/trivy created
job.batch/workloads created
```

**Why This PR?**
_a short description of why this PR is needed_

Fixes #

**Changes**
Changes proposed in this pull request:

*
*

**Checklist:**

* [ ] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] Any new values have been added to the README for the Chart, or helm-docs has been run for the charts that support it.

### CODE REVIEW

**Comment by ivanfetch** [comment]
Hmmm, it looks like to Kube part of the E2E tests passed, but the git worktree is dirty (but from what I'm not sure)?

From the failed output (Kube 1.16 test):

```
>>> kubectl delete namespace insights-agent-zbznlyuagr --timeout 180s
namespace "insights-agent-zbznlyuagr" deleted
>>> kubectl get namespace insights-agent-zbznlyuagr
Namespace 'insights-agent-zbznlyuagr' terminated.
>>> git worktree remove ct_previous_revision073573001
fatal: 'ct_previous_revision073573001' contains modified or untracked files, use --force to delete it
```

**Review by baderbuddy — APPROVED** [review]
LGTM, Thank you! This feels like a big enough change though that I think it's probably a good idea to bump the minor version of the chart instead of the patch version.

**Comment by ivanfetch** [comment]
@baderbuddy Thanks, and done. Good point RE: the version of kubectl could be different in some clusters = different "API" behavior for the chart.

**Comment by ivanfetch** [comment]
I merged master and kept the chart version at a minor difference so this change will not be automatically released. CC @rbren

**Comment by rbren** [comment]
Merged in a separate PR

**Pull request closed without merging**
