### PR TITLE
[polaris] Add: Kubernetes recommanded labels for Polaris

### PR DESCRIPTION
**Pull request by nlamirault**
Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>

**Why This PR?**

Add Kubernetes recommande labels : https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

Fixes #

**Changes**
Changes proposed in this pull request:

*
*

**Checklist:**

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] Any new values have been added to the README for the Chart, or helm-docs has been run for the charts that support it.

### CODE REVIEW

**Comment by rbren** [comment]
@nlamirault can you bump the chart version? Looks like we had a conflicting PR.

**Comment by nlamirault** [comment]
I will do that asap

**Comment by nlamirault** [comment]
@rbren do you have any idea how fix CI ?

**Comment by rbren** [comment]
@nlamirault sorry for losing track of this - should be good to merge once CI passes now

**Pull request merged**
