### PR TITLE
[Insights-Agent] Fix Fleet install for EKS clusters

### PR DESCRIPTION
**Pull request by jonDowdle**
EKS clusters store the EKS version in the `gitVersion`. So curling `https://kubernetes.default.svc/version` returns `v1.20.7-eks-d88609` vs. the expected `v.1.20.7`.

This change only selects values before the delimiter `-`, which returns is what is required when `curl`ing the proper `kubectl` version.

Example: 
```
$ curl -fks https://kubernetes.default.svc/version?timeout=32s |jq -r .gitVersion | cut -d- -f1
v1.20.7
```

**Why This PR?**

To support fleet installation on EKS clusters

Fixes #

**Changes**
Changes proposed in this pull request:

* Supporting fleet installation on EKS clusters by ignoring the EKS data in gitVersion

**Checklist:**

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] Any new values have been added to the README for the Chart, or helm-docs has been run for the charts that support it.

### CODE REVIEW

**Review by rbren — APPROVED** [review]
Good catch!

**Comment by rbren** [comment]
Looks like we should fix it in one more spot too, if you wouldn't mind:

https://github.com/FairwindsOps/charts/blob/7235211a28ec161ec73cf578f5495771112526d6/stable/insights-agent/templates/cronjob-executor/job.yaml#L36

**Comment by rbren** [comment]
nvm - managed to add it to your branch!

**Comment by jonDowdle** [comment]
@rbren ~~happy to test it on a living EKS cluster here (I'm trialing this currently). I'm currently looking for how to point the Helm install as the local version (or my fork). If you have any advice to save me googling around, happy to take it.~~

Edit: Nm - Sarah G answered that Q in an email. Looks like it's working 👍🏻

**Pull request merged**
