### PR TITLE
update helm-docs to 1.3.0, sort based on file order

### PR DESCRIPTION
**Pull request by rbren**
**Why This PR?**
Updates `helm-docs` to latest, and uses the `--sort-values-order=file` argument to sort the value docs based on the order they appear in values.yaml

This gives us more control over how the values appear in the README.

I also updated the values order for Gemini and insights-admission - happy to rearrange others.

**Checklist:**

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] Any new values have been added to the README for the Chart, or helm-docs has been run for the charts that support it.

### CODE REVIEW

**Review by baderbuddy — APPROVED** [review]
This looks good to me. It'll be nice having that control over the values.

**Review by makoscafee — APPROVED** [review]
LGTM

**Review by robertlucido — APPROVED** [review]
LGTMoi

**Comment by sudermanjr** [comment]
Would this mean that people making PRs to the repo would have to pass that flag when making them?

**Review by sudermanjr — CHANGES_REQUESTED** [review]
Would this mean that people making PRs to the repo would have to pass that flag when making them?

This also needs a documentation update in the Contributing.

If we are going to make a sweeping change like this, I would prefer doing the update on all the charts, not just yours

**Comment by rbren** [comment]
Good catch! Updated CONTRIBUTING.

This does affect all charts using helm-docs. Like I said, happy to rearrange other values files if there are any that look particularly off, but I don't think I have quite enough context into each project to know what the best order is.

Maybe the best thing would be for chart owners to push any values.yaml rearrangements they'd like to see to this branch? Also happy to just make a best effort.

**Review by sudermanjr — CHANGES_REQUESTED** [review]
Ah, I see you actually already did what I wanted, which was just running it on all the charts. That's fine for me, the codeowners can rearrange if they want.

The only other ask I have is to update the .pre-commit-config.yaml to use this flag so that those using pre-commit won't get bit by the change.


```
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.3.0
    hooks:
      - id: helm-docs
        args:
          - --sort-values-order=file
```

**Comment by rbren** [comment]
👍 added pre-commit

**Review by sudermanjr — APPROVED** [review]
Just needs a rebase and I think it's probably good to go

**Pull request merged**
